/*
 * GeometryObjectsConstructiongStates.h
 *
 *  Created on: 17 апр. 2015
 *      Author: vadim
 */

#ifndef GEOMETRYOBJECTSCONSTRUCTIONGSTATES_H_
#define GEOMETRYOBJECTSCONSTRUCTIONGSTATES_H_

typedef enum
{

	GEOMETRYOBJECTCONSTRUCTING_NONE,
	GEOMETRYOBJECTCONSTRUCTING_INPROGRESS,
	GEOMETRYOBJECTCONSTRUCTING_COMPLETE

}GeometryObjectsConstructiongStates;



#endif /* GEOMETRYOBJECTSCONSTRUCTIONGSTATES_H_ */
